mqtt:
  server: mqtt://127.0.0.1:1883
serial:
  # Set to your dongle path, e.g. /dev/cu.usbserial-XXXX or /dev/cu.SLAB_USBtoUART
  port: /dev/cu.usbserial-120
  adapter: ezsp
advanced:
  channel: 15
  log_level: info
frontend:
  port: 8081
homeassistant: false
permit_join: true
groups:
  '1':
    friendly_name: shelves
