mqtt:
  server: mqtt://127.0.0.1:1883
serial:
  port: /dev/cu.usbserial-130
  adapter: ember
  rtscts: false
  baudrate: 115200
advanced:
  channel: 15
  log_level: info
  enable_external_js: true
  cache_state: true
  cache_state_persistent: true
  cache_state_send_on_startup: true
  adapter_concurrent: 16
  transmit_power: 20
  availability:
    enabled: true
    active:
      timeout: 2
    passive:
      timeout: 15
frontend:
  enabled: false
homeassistant:
  enabled: false
permit_join: true
groups:
  '1':
    friendly_name: shelves
    optimistic: true
version: 5
devices: {}
